simulation_type:          SWIFT-KIARA             # see docs
halo_id_source:           SNAPSHOT                # see docs; FOF finds haloes without an external catalogue
snapshot_path:            /path/to/snapshot.hdf5
output_dir:               /path/to/output_directory
halo_catalogue_path:      /path/to/catalogue_file  # leave blank if using SNAPSHOT haloes
compress_catalogue:       true


stages:
  find_galaxies:                  true
  properties_core:                true
  properties_ptype_specific:      true
  properties_local_environment:   true
  photometry:                     true


process_ptypes:  # WARNING: removes ptype entirely, e.g. star: false prevents galaxy finding
  gas:    true
  star:   true
  dm:     true
  bh:     true


thresholds:
  min_stars_per_galaxy:   16
  min_gas_per_galaxy:     0
  min_dm_per_halo:        24        # haloes below this threshold will not appear in the catalogue
  nH_lim:                 0.13      # density above which gas is considered dense
  T_lim:                  1.0e+5    # temperature below which gas is considered cold


physics:
  FRAD:   0.1  # radiative efficiency of accretion (epsilon)
  MU:     0.6  # mean mass per-particle (gas)


fof6d:
  b:                0.02                    # position-space linking length = b * mean_interparticle_separation
  velocity_factor:  1                       # velocity-space linking length = velocity_factor * local_velocity_dispersion
  gas_criterion:    COLD_OR_STARFORMING     # criterion for locating galaxy gas
  subhalo_override: true                    # overrides FOF6D subhalo boundaries to the external catalogue


fof_haloes:  # only used if halo_id_source is FOF; haloes below min_dm_per_halo are discarded
  halo_b:               0.2                 # DM linking length = halo_b * mean DM interparticle separation
  halo_attach_ptypes:   [gas, star, bh]     # baryons attached to their nearest DM particle's halo; others get no halo
  

properties:
  radial_quantiles:   # name: fraction of enclosed mass
    r20:        0.2
    half_mass:  0.5
    r80:        0.8
  # NOTE: please pass these as lists, even if single-valued
  aperture_size:    [30]                # kpc
  virial_factors:   [200, 500, 2500]    # factor * critical density
  halo_centre:      MIN_POT


photometry:
  bands:                      ["sdss", "all", "v"]  # auto expands filters (e.g. "sdss" will give sdss_u, sdss_g etc)
  photometry_table_path:      /path/to/photometry_table.hdf5
  extinction_law:             COMPOSITE
  viewing_axis:               Z
  use_dust:                   true
  use_cosmic_extinction:      true
  interpolation_bins:         5000  # for the approximated kernel integral
  kernel_type:                CUBIC
  power_law_alpha:            1.0
  split_age:                  0.01  # Gyr


parallelism:
  n_io_chunks:        10    # for IO reads on datasets, not chunking the pipeline
  cores_per_rank:     4     # number of CPU cores assigned to each MPI rank


logging:
  terminal_output_level:  INFO    # set to DEBUG to see everything, WARNING for only critical notifications
  keep_logs:              False   
  quiet:                  False   # suppresses all terminal output except errors
